name: Matrix Configuration
# The matrix strategy in GitHub Actions allows you to run the same workflow multiple times with different inputs, 
#like OS versions, language versions, or configurations. It’s especially useful for testing across environments or parallel builds.
on: 
    push:
    workflow_dispatch:
jobs:
    deploy:
        
        strategy:
            fail-fast: false
            max-parallel: 2
            matrix:
                os: [ubuntu-latest, ubuntu-20.04, windows-latest]
                images: [hello-world, alpine]
                exclude:
                  - images: alpine
                    os: windows-latest

                include:
                    - images: amd64/alpine
                      os: ubuntu-20.04
        runs-on: ${{ matrix.os}} #dynamic values
        steps:
        - name: Echo Docker info
          run: docker info

        - name: Run Images on ${{ matrix.os }}
          run: docker run ${{ matrix.images }}

    
